import type { SuggestionCategory } from "@/types";

export const SUGGESTION_CATEGORIES: SuggestionCategory[] = [
  {
    name: "Lens Type",
    terms: [
      { label: "14mm ultra-wide", description: "extreme wide angle, dramatic perspective distortion" },
      { label: "24mm wide", description: "wide angle, environmental context" },
      { label: "35mm", description: "natural field of view, street photography" },
      { label: "50mm", description: "closest to human eye, classic look" },
      { label: "85mm portrait", description: "shallow DOF, classic portrait compression" },
      { label: "135mm telephoto", description: "strong background compression, isolated subject" },
      { label: "200mm telephoto", description: "extreme compression, wildlife/sports" },
      { label: "macro lens", description: "extreme close-up, tiny details" },
      { label: "fisheye lens", description: "180° field of view, circular distortion" },
      { label: "anamorphic lens", description: "cinematic horizontal lens flares, oval bokeh" },
      { label: "tilt-shift lens", description: "selective focus, miniature effect" },
      { label: "medium format", description: "large sensor look, creamy bokeh, high detail" },
    ],
  },
  {
    name: "Aperture / Depth of Field",
    terms: [
      { label: "f/1.2 extreme bokeh", description: "razor-thin focus plane, dreamy blur" },
      { label: "f/1.4 shallow DOF", description: "subject isolated from background" },
      { label: "f/2.8 portrait", description: "soft background, still sharp subject" },
      { label: "f/4 moderate DOF", description: "balanced sharpness" },
      { label: "f/8 sharp landscape", description: "front to back sharpness" },
      { label: "f/11 deep focus", description: "everything in focus, landscape standard" },
      { label: "f/16 hyperfocal", description: "maximum depth of field" },
      { label: "f/22 sunstar", description: "starburst effect on light sources" },
    ],
  },
  {
    name: "Lighting",
    terms: [
      { label: "golden hour", description: "warm low-angle sunlight, 1hr after sunrise/before sunset" },
      { label: "blue hour", description: "soft cool twilight just after sunset" },
      { label: "magic hour", description: "diffused warm glow, no harsh shadows" },
      { label: "harsh midday sun", description: "strong shadows, high contrast" },
      { label: "overcast diffused light", description: "soft shadowless light, even exposure" },
      { label: "Rembrandt lighting", description: "triangular shadow on cheek, dramatic portrait" },
      { label: "rim lighting", description: "backlit halo, separates subject from background" },
      { label: "studio softbox", description: "soft controlled artificial light" },
      { label: "neon lights", description: "colorful urban night lighting" },
      { label: "candlelight", description: "warm flickering low key" },
      { label: "bioluminescence", description: "glowing blue-green natural light" },
      { label: "split lighting", description: "half face lit, half in shadow" },
      { label: "chiaroscuro", description: "extreme light/dark contrast, Renaissance style" },
      { label: "motivated lighting", description: "light sourced from visible objects in scene" },
    ],
  },
  {
    name: "Film Stock",
    terms: [
      { label: "Kodak Portra 400", description: "warm skin tones, fine grain, versatile" },
      { label: "Kodak Portra 800", description: "visible grain, high-ISO warmth" },
      { label: "Kodak Ektar 100", description: "vivid saturated colors, ultra-fine grain" },
      { label: "Kodachrome 64", description: "warm reds, classic vintage slide look" },
      { label: "Fuji Velvia 50", description: "hyper-saturated, vivid greens and blues" },
      { label: "Fuji Provia 100F", description: "neutral accurate colors, fine grain" },
      { label: "Fuji 400H", description: "pastel, faded greens, popular for portraits" },
      { label: "Ilford HP5 400", description: "classic black and white, versatile grain" },
      { label: "Ilford Delta 3200", description: "high grain B&W, documentary feel" },
      { label: "Cinestill 800T", description: "tungsten film, orange halation, night scenes" },
      { label: "Lomochrome Purple", description: "surreal purple/green shift" },
      { label: "cross-processed", description: "oversaturated, shifted colors, lo-fi" },
    ],
  },
  {
    name: "Composition",
    terms: [
      { label: "rule of thirds", description: "subject at intersection points" },
      { label: "golden ratio", description: "Fibonacci spiral composition" },
      { label: "leading lines", description: "lines that draw eye to subject" },
      { label: "symmetry", description: "mirror reflection or centered composition" },
      { label: "negative space", description: "empty space emphasizes subject" },
      { label: "framing", description: "natural frame around subject (arch, window)" },
      { label: "Dutch angle", description: "tilted horizon for tension/unease" },
      { label: "worms-eye view", description: "looking up from ground level" },
      { label: "birds-eye view", description: "overhead top-down perspective" },
      { label: "foreground interest", description: "strong element in front layer" },
      { label: "fill the frame", description: "subject dominates entire frame" },
      { label: "layers depth", description: "foreground / midground / background" },
    ],
  },
  {
    name: "Cinema Styles",
    terms: [
      { label: "Kubrick symmetry", description: "one-point perspective, symmetric framing" },
      { label: "Roger Deakins look", description: "Blade Runner 2049 warm-cold contrast" },
      { label: "Wong Kar-wai", description: "blurred motion, neon, melancholy" },
      { label: "Wes Anderson palette", description: "pastel symmetry, flat graphic composition" },
      { label: "film noir", description: "high contrast B&W, venetian blind shadows" },
      { label: "cyberpunk", description: "neon rain, dark city, blue-magenta palette" },
      { label: "neo-noir", description: "color graded modern noir, urban night" },
      { label: "Spielberg close-up", description: "face in frame, emotional reaction" },
      { label: "anamorphic widescreen", description: "2.39:1 aspect, horizontal lens flares" },
      { label: "Super 8 film look", description: "warm saturated, light leaks, grain" },
      { label: "IMAX clarity", description: "ultra-sharp, deep field, documentary epic" },
      { label: "Italian neorealism", description: "gritty natural light, handheld feel" },
    ],
  },
];
